# Generated by Django 3.2.12 on 2022-03-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_cart_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Refund', 'Refund')], default='Pending', max_length=50),
        ),
    ]
