# Generated by Django 3.2.12 on 2022-03-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_payment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='orderded',
        ),
    ]
