# Generated by Django 3.2.12 on 2022-03-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_orderproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='user_cancelled',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
    ]
