# Generated by Django 3.2.12 on 2022-03-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
