# Generated by Django 3.2.12 on 2022-03-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_alter_orderproduct_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
