# Generated by Django 3.2.12 on 2022-03-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_coupon_couponused'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
