# Generated by Django 3.2.12 on 2022-03-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_couponused_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_limit',
            field=models.IntegerField(null=True),
        ),
    ]
