# Generated by Django 3.2.12 on 2022-03-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_alter_coupon_coupon_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponused',
            name='applied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='couponused',
            name='loss',
            field=models.FloatField(blank=True, default=0, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='couponused',
            name='used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
