# Generated by Django 3.2.12 on 2022-03-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_auto_20220318_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='coupon_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
