# Generated by Django 3.2.12 on 2022-03-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
