# Generated by Django 3.2.12 on 2022-03-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0031_couponcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponCode',
        ),
    ]
