# Generated by Django 3.2.12 on 2022-03-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0033_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_use_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
