# Generated by Django 3.2.12 on 2022-03-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0038_remove_orderproduct_coupon_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
