# Generated by Django 3.2.12 on 2022-03-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0040_auto_20220321_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
