# Generated by Django 3.2.12 on 2022-03-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0047_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='user_returned',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
    ]
