# Generated by Django 3.2.12 on 2022-03-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0048_orderproduct_user_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptionfour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionthree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptiontwo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
