# Generated by Django 3.2.12 on 2022-03-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0050_bannerupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerupdate',
            name='banner_name',
        ),
    ]
