# Generated by Django 3.2.12 on 2022-05-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0054_product_users_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
    ]
